# Generated by Django 6.0.1 on 2026-01-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='Url',
        ),
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
