# Generated by Django 6.0.1 on 2026-01-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_phone_url_phone_description_phone_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='model',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
