# Generated by Django 6.0.1 on 2026-01-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_phone_reviews_alter_laptop_price_alter_phone_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='reviews',
            field=models.CharField(default=0),
        ),
    ]
