# Generated by Django 6.0.1 on 2026-01-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_phone_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
